spring.config.import=optional:file:.env[.properties]

# URL do banco
spring.datasource.url=${DATABASE_URL}

# Login
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_USERPASS}

# Configurações de banco
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true