# 1. Conexão com o Banco (Sem variáveis, direto ao ponto)
spring.datasource.url=jdbc:mysql://localhost:3306/gerenciador_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=devuser
spring.datasource.password=1234

# 2. Configurações do Hibernate (A mágica de criar tabelas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true